// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBllJAEn7G_gF85hsBtmxWq8lYaRx-5rU4',
    appId: '1:118083220738:web:309c8c28da03319f837e1b',
    messagingSenderId: '118083220738',
    projectId: 'jotech-nuc',
    authDomain: 'jotech-nuc.firebaseapp.com',
    storageBucket: 'jotech-nuc.appspot.com',
    measurementId: 'G-LZJ6SG4834',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABLPEYFEjCQGyeS15cOsUJbCVMijZR3fo',
    appId: '1:118083220738:android:67c8456195400a13837e1b',
    messagingSenderId: '118083220738',
    projectId: 'jotech-nuc',
    storageBucket: 'jotech-nuc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36pJA_G-A-va8frZkcUnTLSpNdejd3J0',
    appId: '1:118083220738:ios:4c70ddae8daa58b5837e1b',
    messagingSenderId: '118083220738',
    projectId: 'jotech-nuc',
    storageBucket: 'jotech-nuc.appspot.com',
    iosBundleId: 'com.example.jotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD36pJA_G-A-va8frZkcUnTLSpNdejd3J0',
    appId: '1:118083220738:ios:4c70ddae8daa58b5837e1b',
    messagingSenderId: '118083220738',
    projectId: 'jotech-nuc',
    storageBucket: 'jotech-nuc.appspot.com',
    iosBundleId: 'com.example.jotech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBllJAEn7G_gF85hsBtmxWq8lYaRx-5rU4',
    appId: '1:118083220738:web:c3b9fed067713ab9837e1b',
    messagingSenderId: '118083220738',
    projectId: 'jotech-nuc',
    authDomain: 'jotech-nuc.firebaseapp.com',
    storageBucket: 'jotech-nuc.appspot.com',
    measurementId: 'G-0H2MSJP7RT',
  );
}
